### ISSUE TITLE
OutputAssertionBuilder:satisfies's lifetime limits its utility

### ISSUE THREAD

**Issue by nwalfield** [killercup/assert_cli#120]
I'm a bit confused about the lifetime used for the callback in [`OutputAssertionBuilder::satisfies`](https://docs.rs/assert_cli/0.6.3/assert_cli/struct.OutputAssertionBuilder.html#method.satisfies), which has the following signature:

```
pub fn satisfies<F, M>(self, pred: F, msg: M) -> Assert where
    F: 'static + Fn(&str) -> bool,
    M: Into<String>, 
```

Is there a reason that `'static` is used?

I have a function `t(filename: &str, count: usize)`.  I want to use `Assert::cargo_binary` to call my tool on `filename`, and then use `satisfies` to make sure the number of objects that is produces is `count`.  But that doesn't work, because:

```
59 |                 r = r.stdout().satisfies(|output| {
   |                                          ^^^^^^^^ may outlive borrowed value `count`
...
```

Is there a reason that `pred` is `'static`?  Is there another way to do what I want?

Thanks for your help!

- `assert_cli` version: 0.6.3 (`Cargo.lock` checksum: `a29ab7c0ed62970beb0534d637a8688842506d0ff9157de83286dacd065c8149`)
- Rust version: 1.46.0 (04488afe3 2020-08-24)
- OS and version: Debian Stable plus a bit of testing

**Comment by epage** [comment]
`assert_cli` has been superseded by `assert_cmd` which I believe does relax this requirement because it evaluates assertions immediately rather than queuing them up.

See https://docs.rs/assert_cmd/1.0.1/assert_cmd/

**Comment by nwalfield** [comment]
Thanks a lot for following up.  I had used assert_cli years ago, and just copied the code to another project and modified it.  Perhaps it makes sense to upload a new version with a few deprecated tags.  Thanks!
