### ISSUE TITLE
try to avoid multiline panics

### ISSUE THREAD

**Issue by colin-kiegel** [killercup/assert_cli#14]
I started poking around and found this panic message

```
        thread 'tests::test' panicked at 'Assert CLI failure:
Expected output to contain
41
but could not find it in
42
', /some/file
```

This reminds me that my atom IDE currently fails to parse multi-line panics - I just filed this issue yesterday. ^^ https://github.com/AtomBuild/atom-build-cargo/issues/85

When I compare it with the output of `assert_eq!(42, 41);`
```
... 'assertion failed: `(left == right)` (left: `42`, right: `41`)' ...
```

How about something similar to what we already know from std:
```
... 'CLI assertion failed: `(Output expected to contain `41`)` (observed: `42`)' ...
```

**Comment by killercup** [comment]
I only did that because the print_exactly panic is a full, colorful diff anyway… and instead of `42` and `41` the values could well be `Lorem ipsum dolor` and the full help message…

**Comment by colin-kiegel** [comment]
Ok, interesting. Would it be an option to print to stderr before panicking?

stderr output could be multi-line, and the panic only a one-line summary? That might lead to garbled output, when multiple tests run concurrently - I'm not really sure. I'm just thinking out loud about alternatives. :-)

If you ask me, at least the case above looks nicer in one line.

**Comment by colin-kiegel** [comment]
I will submit a suggestion in a PR. :-)
