### ISSUE TITLE
The I-don't-care-about-the-status feature

### ISSUE THREAD

**Issue by killercup** [killercup/assert_cli#23]
People might not care whether a program succeeds or fails, but we currently default to asserting success and you can only switch to "assert failure" not to "I don't care".

We already talked about this a bit here:

- https://github.com/killercup/assert_cli/pull/16#discussion_r107287454

**Comment by epage** [comment]
Maybe it could be called `.ignore_status()`?

**Comment by killercup** [comment]
Sounds good!

Ed Page <notifications@github.com> schrieb am Fr. 13. Okt. 2017 um 02:55:
