### ISSUE TITLE
Can't validate stderr/stdout don't have some text

### ISSUE THREAD

**Issue by epage** [killercup/assert_cli#31]
In upgrading cobalt.rs to 0.4, I found that they tested for the absence of text (to verify logging levels).  There doesn't seem to be a way to do this with the new API

See https://github.com/cobalt-org/cobalt.rs/blob/master/tests/cli.rs

**Comment by killercup** [comment]
That's a valid feature request. :) I'm currently redesigning the way we internally handle output assertions (#24), and want to have multiple fuzzy matchers some time in the future (#20). Maybe we can combine this with negative matches? Shouldn't be too hard.

I'm thinking of something like

```rust
#[test]
fn negative_fuzzy() {
    Assert::command("echo foo")
        .prints("foo")
        .doesnt_print("bar")
        .unwrap();
}
```
