### ISSUE TITLE
Make Assert::command and with_args take AsRef<OsStr> args

### ISSUE THREAD

**Issue by luser** [killercup/assert_cli#59]
First off, I just learned about assert_cli today and I'm excited to start using it!

All of the methods on [`std::process:Command`](https://doc.rust-lang.org/std/process/struct.Command.html) for the executable name and commandline arguments take `T: AsRef<OsStr>`, so you can pass `&str` but also `&Path` and other useful things. It would be nice if `Assert::command` and `Assert::with_args` took the same type of arguments so that users could pass in a larger variety of types.

Specifically, I have the path to the executable I want to run as a `PathBuf`, so I can't pass it directly.

This will require `Assert` to store `cmd` as `Vec<OsString>` instead of `Vec<String>`, but it shouldn't cause any issues.

**Comment by epage** [comment]
Thanks for the feedback!

I agree that it'd be a good thing for us to make the API more accepting of different string types, much like what was done with [`Environment`](https://github.com/Freyskeyd/environment).

**Comment by killercup** [comment]
Yep, we should take `AsRef<OsStr>`!
