### ISSUE TITLE
Have an option to ignore output of tested command

### ISSUE THREAD

**Issue by Lindenk** [killercup/assert_cli#6]
Currently it is impossible to only check if the command returned an error value or not. Ideally, the output could be optionally ignored and just the return code is checked.

**Comment by killercup** [comment]
Sounds okay to me, although I would actually like to have a 'fuzzy' output matching, too (an let the empty string be a special case that always matches).

Do you want to implement this? I don't have a need for this right now, so I'll probably not implement this anytime soon.

**Comment by Lindenk** [comment]
Hmm, how about some kind of mixed regex based matching then? Something like:

```
"The result is: r/[0-9+/"
```

Either way, I would be glad to implement this. It has a direct use case for one of my current projects right now.

**Comment by killercup** [comment]
Cool! I'll gladly await you PR :)

Using regex sounds good. Maybe put it behind a cargo feature, though, as not everyone might want to have that (rather large) dependency for something as simple as assert_cli.
