### ISSUE TITLE
Add a crates badge to readme

### ISSUE THREAD

**Issue by epage** [killercup/assert_cli#63]
I got this feedback from someone who doesn't trust the version in the dependency example and always goes to crates.io to check the published version.

**Comment by killercup** [comment]
Haha, fine:

![crates.io](https://img.shields.io/crates/l/assert_cli.svg)

Let's also add a license badge while we're at it!

![license](https://img.shields.io/crates/v/assert_cli.svg)

**Comment by epage** [comment]
Closed by #71
