### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by epage** [killercup/assert_cli#64]
- Appropriate way to ask questions / get feedback
- Expectations for a PR
- (Maybe) Release process

For example: https://github.com/cobalt-org/liquid-rust/blob/master/CONTRIBUTING.md

**Comment by killercup** [comment]
Sounds good. In general I'd want to emphasize that Github issues is the preferred way of getting help/suggestion features/reporting bugs and opening an issue before doing a PR is a good idea.

**Comment by epage** [comment]
> In general I'd want to emphasize that Github issues is the preferred way of getting help/suggestion features/reporting bugs 

Good to know and get documented.  I know when I approach a project, if I have questions, if there isn't a gitter channel, I walk away because I assume others prefer issues not being used for support or questions.

**Comment by killercup** [comment]
Interesting! My experience has quite often been that a lot of questions are valid "we need better docs" issues, or at least will turn up when someone else searches for the same thing.

I usually don't create Gitter channels for small projects… but I guess assert_cli is not necessarily small any more. If you want, we can add one. I'm on Gitter anyway (~~trolling~~ helping people in the diesel rooms).

**Comment by epage** [comment]
Nah, as long as its documented so people know how to reach out

**Comment by epage** [comment]
Closed by #71
