### ISSUE TITLE
Assert type isn't must_use so writing an assertion without unwrap gives no warning

### ISSUE THREAD

**Issue by porglezomp** [killercup/assert_cli#66]
My first test was
```rust
assert_cli::Assert::main_binary()
    .succeeds()
    .and()
    .stdout()
    .is("hi");
```
which does nothing since it's not unwrapped.
`#[must_use]` on the `Assert` type should probably fix this?

**Comment by killercup** [comment]
Very good catch!

Yes, we should add `#[must_use]` to the type.
