### ISSUE TITLE
Help people find other relevant CLI testing tools

### ISSUE THREAD

**Issue by epage** [killercup/assert_cli#69]
The idea is to add to the readme other relevant cli testing tools.

Suggestions:
- [dir-diff](https://crates.io/crates/dir-diff) (granted, I feel it needs more features which I will attempt to add)
- [tempdir](https://github.com/rust-lang-nursery/tempdir)

**Comment by epage** [comment]
Maybe `duct` for people needing more than one-shot runs of programs but needing to coordinate them?

**Comment by killercup** [comment]
Great idea! I think there are a few neat ways to test apps build with clap where you just pass the args to a main-like fn, so it becomes more unit-testable and you don't need assert_cli for that at all.

**Comment by epage** [comment]
Closed by #71
