### ISSUE TITLE
Have an option to run the built rust binary implicitly

### ISSUE THREAD

**Issue by Lindenk** [killercup/assert_cli#9]
Although not a major feature, it would be nice if assert_cli could, by default, run the binary built by the current project (if there is one).

So, if  assert_cli is being used in tests for a project foobar, the macro could be used like so:

``` rust
assert_cli!(&["arg1", "arg2"] => Success);
```

and the unspecified command would be set to a default of `$PROJECT_HOME/target/debug/$PROJECT_NAME`.

Just an idea to put on the table.

**Comment by killercup** [comment]
Sure, sounds like a reasonable default. Maybe use `cargo run --`?
Linden Krouse <notifications@github.com> schrieb am So. 10. Juli 2016 um
17:35:

**Comment by Lindenk** [comment]
Yeah, that sounds like the best way to implement it in case directories change.
